version: "3"

services:
  postgresql:
    image: postgres
    container_name: test
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-test
    ports:
      - "6379-6379"
